language: node_js
cache:
  yarn: true
notifications:
  email: false
branches:
  only:
    - master
    - dev
node_js:
  - "8"
env:
  global:
    - NODE_ENV=test
install:
  - yarn
before_script:
  - node -v
script:
  - yarn test
